OnlineWebCourse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
import xadmin

from apps.users.views import LoginView, LogoutView, RegisterView, SendSmsView, DynamicLoginView
from apps.organizations.views import OrgView

import apps.organizations.views

urlpatterns = [
                  path('', TemplateView.as_view(template_name='index.html'), name="index"),
                  path('login/', LoginView.as_view(), name="login"),
                  path('d_login/', DynamicLoginView.as_view(), name="d_login"),
                  path('logout/', LogoutView.as_view(), name="logout"),
                  path('register/', RegisterView.as_view(), name="register"),
                  path('send_sms/', csrf_exempt(SendSmsView.as_view()), name='send_sms'),
                  path('xadmin/', xadmin.site.urls),
                  path('captcha/', include('captcha.urls')),
                  path('org/', include(("apps.organizations.urls", "organizations"), namespace="org")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/organizations/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2023/3/3 07:36
# @Author  : tianpeng
# @FileName: urls
from django.urls import path

from apps.organizations.views import OrgView, UserConsultView, OrgHomeView

urlpatterns = [
    path('list/', OrgView.as_view(), name="list"),
    path('add_ask/', UserConsultView.as_view(), name="add_ask"),
    path('<int:org_id>/', OrgHomeView.as_view(), name="home")
]

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %}
    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %} " type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %} " type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>服务电话：<b>33333333</b></p></div>
                    <!--登录后跳转-->


                    <a style="color:white" class="fr registerbtn" href="register.html">注册</a>
                    <a style="color:white" class="fr loginbtn" href="login.html">登录</a>


                </div>
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="/"><img class="fl" src="{% static 'images/logo.jpg' %} "/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                公开课
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %} "/>
                    </div>
                </div>
            </div>


            <nav>
                <div class="nav">
                    <div class="wp">
                        <ul>
                            <li><a href="/">首页</a></li>
                            <li>
                                <a href="course-list.html">
                                    公开课<img class="hot" src="{% static 'images/nav_hot.png' %} ">
                                </a>
                            </li>
                            <li>
                                <a href="teachers-list.html">授课教师</a>
                            </li>
                            <li class="active"><a href="{% url "org:list" %}">授课机构</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="{% static 'images/footlogo.png' %} "/></a></li>
                <li class="code"><img src="{% static 'images/code.jpg' %} "/>
                    <p class="center">扫描关注微信</p></li>
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %} "/>
                    <p class="tell">33333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
            <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="{% static 'js/selectUi.js' %} " type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %} " type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %} "></script>
<script src="{% static 'js/plugins/layer/layer.js' %} "></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %} " type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %} " type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %} " type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %} " type="text/javascript"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>

templates/org-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    课程机构列表 - 慕学在线网
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>课程机构</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class='left'>
                <div class="listoptions">
                    <ul>
                        <li>
                            <h2>机构类别</h2>
                            <div class="cont">
                                <a href="?city={{ city_id }}"><span
                                        class="{% if not category %}active2{% endif %}">全部</span></a>

                                <a href="?ct=1&city={{ city_id }}"><span
                                        class="{% if category == '1' %}active2{% endif %}">培训机构</span></a>

                                <a href="?ct=2&city={{ city_id }}"><span
                                        class="{% if category == '2' %}active2{% endif %}">高校</span></a>

                                <a href="?ct=3&city={{ city_id }}"><span
                                        class="{% if category == '3' %}active2{% endif %}">个人</span></a>

                            </div>
                        </li>
                        <li>
                            <h2>所在地区</h2>
                            <div class="more">更多</div>
                            <div class="cont">
                                <a href="?ct={{ category }}"><span
                                        class="{% if not city_id %}active2{% endif %}">全部</span></a>
                                {% for city in all_citys %}
                                    <a href="?city={{ city.id }}&ct={{ category }}"><span
                                            class="{% if city_id == city.id|stringformat:'i' %}active2{% endif %}">{{ city.name }}</span></a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="all">共<span class="key">{{ org_nums }}</span>家</div>
                <div class="butler_list company list">
                    <div class="layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li class="{% ifequal sort_org "" %}active{% endifequal %}"><a
                                        href="?ct=&city=">全部</a></li>
                                <li class="{% ifequal sort_org "students" %}active{% endifequal %}"><a
                                        href="?sort=students&ct={{ category }}&city={{ city_id }}">学习人数 &#8595;</a>
                                </li>
                                <li class="{% ifequal sort_org "courses" %}active{% endifequal %}"><a
                                        href="?sort=courses&ct={{ category }}&city={{ city_id }}">课程数 &#8595;</a>
                                </li>
                            </ul>
                        </div>
                        {% for org in all_orgs.object_list %}
                            <dl class="des difdes">
                                <dt>
                                    <a href="org-detail-homepage.html">
                                        <img width="200" height="120" class="scrollLoading"
                                             data-url="{{ MEDIA_URL }}{{ org.logo }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <div class="clearfix">
                                        <a href="org-detail-homepage.html">
                                            <h1>{{ org.name }}</h1>
                                            <div class="pic fl">
                                                {% if org.is_auth %}
                                                    <img src="{% static 'images/authentication.png' %} "/>
                                                {% endif %}
                                                {% if org.is_gold %}
                                                    <img src="{% static 'images/gold.png' %} "/>
                                                {% endif %}
                                            </div>
                                        </a>
                                    </div>
                                    <ul class="cont">
                                        <li class="first"><p class="pic9">课程数：<span>{{ org.course_nums }}</span></p>
                                            <p class="c7">学习人数：<span>{{ org.students }}</span></p></li>
                                        <li class="c8" style="padding-left:18px;">{{ org.address }}</li>
                                        <li class="pic10" style="padding-left:18px;">经典课程：
                                            {% if org.courses %}
                                                {% for c in org.courses %}
                                                    <a href="/diary/19/">{{ c.name }}</a>
                                                {% endfor %}
                                            {% else %}
                                                无
                                            {% endif %}

                                        </li>
                                    </ul>
                                </dd>
                                <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                            </dl>
                        {% endfor %}

                    </div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {% if all_orgs.has_previous %}
                                <li class="long"><a href="?{{ all_orgs.previous_page_number.querystring }}">上一页</a>
                                </li>
                            {% endif %}
                            {% for page in all_orgs.pages %}
                                {% if page %}
                                    {% ifequal page all_orgs.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none">...</li>
                                {% endif %}
                            {% endfor %}
                            {% if all_orgs.has_next %}
                                <li class="long"><a href="?{{ all_orgs.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="right companyright">
                <div class="head">我要学习</div>
                <form class="rightform" id="jsStayForm">
                    <div>
                        <img src="{% static 'images/rightform1.png' %} "/>
                        <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25"/>
                    </div>
                    <div>
                        <img src="{% static 'images/rightform2.png' %} "/>
                        <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                    </div>
                    <div>
                        <img src="{% static 'images/rightform3.png' %} "/>
                        <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50"/>
                    </div>
                    <p class="error company-tips" id="jsCompanyTips"></p>
                    <input class="btn" type="text" id="jsStayBtn" value="立即咨询 >"/>
                    {% csrf_token %}
                </form>
            </div>
            <div class="right companyrank layout">
                <div class="head">授课机构排名</div>

                {% for org in hot_orgs %}
                    <dl class="des">
                        <dt class="num fl">{{ forloop.counter }}</dt>
                        <dd>
                            <a href="/company/2/"><h1>{{ org.name }}</h1></a>
                            <p>{{ org.address }}</p>
                        </dd>
                    </dl>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}
{% block custom_js %}
    <script>
        $(function () {
            $(document).ready(function () {
                $('#jsStayBtn').on('click', function () {
                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "{% url "org:add_ask"%}",
                        data: $('#jsStayForm').serialize(),
                        async: true,
                        success: function (data) {
                            if (data.status == 'success') {
                                $('#jsStayForm')[0].reset();
                                $('#jsCompanyTips').html("");
                                alert("提交成功")
                            } else if (data.status == 'fail') {
                                $('#jsCompanyTips').html(data.msg)
                            }
                        },
                    });
                });
            });
        })

    </script>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}机构首页{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">

            <div class="top">
                <div class="wp">
                    <div class="fl">
                        <p>联系方式：<b>3333333333</b></p>
                    </div>
                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/>
                                </dd>
                                <dt><img width="20" height="20" src="/static/media/image/2016/12/default_big_14.png"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="/static/media/image/2016/12/default_big_14.png"/>
                                    </dt>
                                    <dd>
                                        <h2>{{ user.username }}</h2>
                                        <p>bobby</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="usercenter-info.html">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url "register" %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url "login" %}">登录</a>
                    {% endif %}
                </div>
            </div>


            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="../media/org/2016/11/imooc.png"/>
                    <div class="head fl">
                        <h1>
                            慕课网
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin
                 " data-favid="22" data-fav-type="1">
                        收藏
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:list' %}">课程机构</a>></li>
            <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
    </div>
</section>

<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="active2"><a href="org-detail-homepage.html">机构首页</a></li>
                <li class=""><a href="org-detail-course.html">机构课程</a></li>
                <li class=""><a href="org-detail-desc.html">机构介绍</a></li>
                <li class=""><a href="org-detail-teachers.html">机构讲师</a></li>
            </ul>
        </div>
        {% block right_form %}

        {% endblock %}
        <div class="right companycenter layout">
            <div class="head">
                <h1>机构教师</h1>
                <a class="green fr more" href="org-detail-teachers.html">查看更多 > </a>
            </div>

            <div class="diarys">
                <div class="module5 share company-diary-box" style="padding:10px 0;">
                    <div class="left">
                        <img class="pic" src="../media/teacher/2016/11/aobama_CXWwMef.png"/>
                        <p>昵称：bobby</p>
                    </div>
                    <div class="right">
                        <div class="top">
                            <div class="fl">
                                <a href=""><h1>java开发教程</h1></a>
                                <span>发表于：2015-10-12</span>
                            </div>
                        </div>
                        <div class="middle" style="border-bottom:0;">课程介绍</div>
                    </div>
                </div>
            </div>


        </div>
        <div class="right companycenter layout">
            <div class="head">
                <h1>机构介绍</h1>
                <a class="green fr more" href="org-detail-desc.html">查看更多 > </a>
            </div>
            <div class="cont">&nbsp; &nbsp; <p>&nbsp; &nbsp;</p>
                <h1 class="ue_t" label="Title center" name="tc"
                    style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;">
                    <span style="color:#c0504d;">[键入文档标题]</span></h1>
                <p style="text-align:center;"><strong class="ue_t">[键入文档副标题]</strong></p>
                <h3><span class="ue_t" style="font-family:幼圆">[标题 1]</span></h3>
                <p class="ue_t" style="text-indent:2em;">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。
                    您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。
                    您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p>
                <p class="ue_t" style="text-indent:2em;"><img
                        src="../media/courses/ueditor/57aa86a0000145c512000460_20161210234050_865.jpg" title=""
                        alt="57aa86a0000145c512000460.jpg"/></p>
                <h3><span class="ue_t" style="font-family:幼圆">[标题 2]</span></h3>
                <p>
                    <img src="http://api.map.baidu.com/staticimage?center=116.410899,39.863624&zoom=11&width=530&height=340&markers=116.404,39.915"
                         width="530" height="340"/></p>
                <p class="ue_t" style="text-indent:2em;">在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。
                    您还可以使用“开始”选项卡上的其他控件来直接设置文本格式。大多数控件都允许您选择是使用当前主题外观，还是使用某种直接指定的格式。</p>
                <h3><span class="ue_t" style="font-family:幼圆">[标题 3]</span></h3>
                <p>2016-12-10</p>
                <p class="ue_t">对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。
                    您可以使用这些库来插入表格、页眉、页脚、列表、封面以及其他文档构建基块。
                    您创建的图片、图表或关系图也将与当前的文档外观协调一致。</p>
                <p class="ue_t"><br/></p>
                <p><br/></p>
                <p><br/></p><a href="/company/desc/22/"><span class="green">[查看更多]</span></a></div>
        </div>


</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>

<script type="text/javascript">
    {% block custom_js %}{% endblock %}
    //收藏分享
    //收藏分享
    function add_fav(current_elem, fav_id, fav_type) {
        $.ajax({
            cache: false,
            type: "POST",
            url: "/org/add_fav/",
            data: {'fav_id': fav_id, 'fav_type': fav_type},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "login.html";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == 'success') {
                    current_elem.text(data.msg)
                }
            },
        });
    }

    $(document).ready(function () {
        $('.collectionbtn').on('click', function () {
            add_fav($(this), 1, 2);
        });
    });
    $(function () {
        var $precision = $('.precision'),
            score = $precision.attr('data-star-scope'),
            option = {
                half: true,
                path: '{% static 'images/' %}',
                precision: true,
                size: 24,
                starOff: 'g_star.png',
                starOn: 'r_star.png',
                starHalf: 'h_star.png',
                hints: ['极差', '差', '一般', '好评', '非常满意'],
                noRatedMsg: '暂时还未获得评价！',
                readOnly: true,
                score: score
            };
        $precision.raty(option);

        $(document).ready(function () {
            $('.jsFavBtn').on('click', function () {
                var type = $(this).attr('data-fav-type');
                if (type == '1') {
                    favPraise($(this), 'fav', 1, '收藏');

                } else if (type == '3') {
                    favPraise($(this), 'fav', 3);

                } else if (type == '11') {
                    favPraise($(this), 'pra', 1);

                } else if (type == '4') {
                    favPraise($(this), 'fav', 4);

                }
            });
        });
    })
</script>


<script type="text/javascript">
    $(function () {
        $('.recordbtn1').click(function () {
            $('.recordbox1').show();
        });
        $('.recordbtn2').click(function () {
            $('.recordbox2').show();
        });

        $('.imgslide').unslider({
            speed: 500,               //  The speed to animate each slide (in milliseconds)
            delay: 3000,              //  The delay between slide animations (in milliseconds)
            complete: function () {
            },  //  A function that gets called after every slide animation
            keys: true,               //  Enable keyboard (left, right) arrow shortcuts
            dots: true,               //  Display dot navigation
            fluid: false              //  Support responsive design. May break non-responsive designs
        });
        var unslider = $('.imgslide').unslider();
        $('.unslider-arrow').click(function () {
            var fn = this.className.split(' ')[1];
            unslider.data('unslider')[fn]();
        });
    });
</script>

</body>
</html>